import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { IonContent, IonHeader, IonToolbar, IonTitle, IonButton, IonIcon, IonItem, IonInput, IonLabel, IonSegment, IonSegmentButton, IonImg, IonText, ModalController, AlertController } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { mail, lockClosed, person } from 'ionicons/icons';
import { SuccessModalComponent } from '../../components/success-modal/success-modal.component';
import { AuthService } from '../../../../infrastructure/services/auth.service';
import { User } from '../../../../domain/models/user.entity';

@Component({
    selector: 'app-login',
    templateUrl: './login.page.html',
    styleUrls: ['./login.page.scss'],
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, IonContent, IonHeader, IonToolbar, IonTitle, IonButton, IonIcon, IonItem, IonInput, IonLabel, IonSegment, IonSegmentButton]
})
export class LoginPage implements OnInit {
    loginForm: FormGroup;
    registerForm: FormGroup;
    segmentValue: 'login' | 'register' = 'login';
    logoUrl = 'assets/shared/images/logo.jpg';

    constructor(
        private fb: FormBuilder,
        private router: Router,
        private modalCtrl: ModalController,
        private authService: AuthService,
        private alertCtrl: AlertController
    ) {
        addIcons({ mail, lockClosed, person });
        this.loginForm = this.fb.group({
            email: ['', [Validators.required, Validators.email]],
            password: ['', [Validators.required, Validators.minLength(6)]]
        });

        this.registerForm = this.fb.group({
            firstName: ['', [Validators.required, Validators.minLength(2)]],
            lastName: ['', [Validators.required, Validators.minLength(2)]],
            email: ['', [Validators.required, Validators.email]],
            password: ['', [Validators.required, Validators.minLength(6)]],
            confirmPassword: ['', [Validators.required]]
        }, { validators: this.passwordMatchValidator });
    }

    passwordMatchValidator(form: FormGroup) {
        const password = form.get('password');
        const confirmPassword = form.get('confirmPassword');
        return password && confirmPassword && password.value === confirmPassword.value ? null : { mismatch: true };
    }

    ngOnInit() { }

    onSegmentChanged(event: any) {
        this.segmentValue = event.detail.value;
    }

    async onSubmit() {
        if (this.segmentValue === 'login' && this.loginForm.valid) {
            await this.handleLogin();
        } else if (this.segmentValue === 'register' && this.registerForm.valid) {
            await this.handleRegister();
        }
    }

    async handleLogin() {
        const { email, password } = this.loginForm.value;

        this.authService.login(email, password).subscribe({
            next: async (user) => {
                await this.showSuccessModal();
                this.router.navigate(['/home']);
            },
            error: async (err) => {
                await this.showAlert('Error', err.message || 'Credenciales incorrectas');
            }
        });
    }

    async handleRegister() {
        const formValue = this.registerForm.value;

        // Construct User object (mocking some required fields for now)
        const newUser: User = {
            id: '', // Will be generated by service
            firstName: formValue.firstName,
            lastName: formValue.lastName,
            email: formValue.email,
            userName: formValue.email.split('@')[0], // Generate username from email
            password: formValue.password,
            role: 'Visitante',
            birthdate: '2000-01-01', // Default for now
            nationality: 'MX',
            phoneNumber: '',
            gender: 'OTHER',
            status: 'ACTIVE',
            profilePicture: 'assets/icon/favicon.png', // Default
            address: { // Default empty address
                street: '',
                externalNumber: '',
                colony: '',
                city: '',
                state: '',
                zipCode: '',
                country: 'México'
            }
        };

        this.authService.register(newUser).subscribe({
            next: async (user) => {
                await this.showSuccessModal();
                this.router.navigate(['/home']);
            },
            error: async (err) => {
                await this.showAlert('Error', err.message || 'No se pudo registrar');
            }
        });
    }

    async showSuccessModal() {
        const modal = await this.modalCtrl.create({
            component: SuccessModalComponent,
            cssClass: 'auto-height-modal',
            backdropDismiss: false,
            componentProps: {}
        });

        await modal.present();
        await modal.onWillDismiss();
    }

    async showAlert(header: string, message: string) {
        const alert = await this.alertCtrl.create({
            header,
            message,
            buttons: ['OK']
        });
        await alert.present();
    }
}
